name: FastAPI CI and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t fastapi-app .

    - name: Stop and remove existing container (if any)
      run: |
        docker stop fastapi-app || true
        docker rm fastapi-app || true

    - name: Run Docker container
      run: |
        docker run -d --restart unless-stopped -p 80:80 --name fastapi-app fastapi-app
