name: FastAPI CI and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: self-hosted  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        echo "Running basic import test"
        python -c "import app.main"

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa.pem
        chmod 600 ~/.ssh/id_rsa.pem
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pem ubuntu@"$EC2_PUBLIC_IP" << 'EOF'
          cd /home/ubuntu/fastapi-crud || git clone https://github.com/vipunsanjana/Github-Actions-Python-EC2.git
          cd fastapi-crud
          git pull origin main
          source ~/venv/bin/activate || python3 -m venv ~/venv && source ~/venv/bin/activate
          pip install -r requirements.txt
          pkill uvicorn || true
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
        EOF
